// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiurFrVgrskQsl-Hz0i52aQHyu8rqp_mw',
    appId: '1:96004579911:android:c1d08d7352258df19fc762',
    messagingSenderId: '96004579911',
    projectId: 'cs-academy-tvm',
    storageBucket: 'cs-academy-tvm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhiGyt6ouyRwbf4HXq5IYypg_5xoeKXBE',
    appId: '1:96004579911:ios:37bd976d58a52e049fc762',
    messagingSenderId: '96004579911',
    projectId: 'cs-academy-tvm',
    storageBucket: 'cs-academy-tvm.appspot.com',
    iosBundleId: 'com.example.csacademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhiGyt6ouyRwbf4HXq5IYypg_5xoeKXBE',
    appId: '1:96004579911:ios:37bd976d58a52e049fc762',
    messagingSenderId: '96004579911',
    projectId: 'cs-academy-tvm',
    storageBucket: 'cs-academy-tvm.appspot.com',
    iosBundleId: 'com.example.csacademy',
  );
}
